import type { Meta, StoryObj } from "@storybook/react";
import Buttons from "./Buttons";
import Badges from "./Badges";
import KpiGrid from "./KpiGrid";
import TrustGauge from "./TrustGauge";
import ExecutionTimeline from "./ExecutionTimeline";
import DataTable from "./DataTable";
import Recommendation from "./Recommendation";
import StatusBanner from "./StatusBanner";
import ExecSummary from "./ExecSummary";
import ImpactRollup from "./ImpactRollup";
import ScenarioProjection from "./ScenarioProjection";
import Chat from "./Chat";
import { AiLaunchButton } from "./AiLaunchButton";
import { AiLoader } from "./AiLoader";
import { AiModalChat } from "./AiModalChat";
import { AiChatHistory } from "./AiChatHistory";
import { AiFeedbackSources } from "./AiFeedbackSources";
import { DagGraphKit } from "./DagGraphKit";

const meta: Meta = { title: "Composites", tags: ["autodocs"], parameters: { layout: "fullscreen" } };
export default meta;

export const ButtonsStory: StoryObj = { name: "Buttons", render: () => <Buttons /> };
export const BadgesStory: StoryObj = { name: "Badges", render: () => <Badges /> };
export const KpiGridStory: StoryObj = { name: "KPI Grid", render: () => <KpiGrid /> };
export const TrustGaugeStory: StoryObj = { name: "Trust Gauge", render: () => <TrustGauge /> };
export const ExecutionTimelineStory: StoryObj = { name: "Execution Timeline", render: () => <ExecutionTimeline /> };
export const TableStory: StoryObj = { name: "Table", render: () => <DataTable /> };
export const RecommendationStory: StoryObj = { name: "Recommendation", render: () => <Recommendation /> };
export const StatusBannerStory: StoryObj = { name: "Status Banner", render: () => <StatusBanner /> };
export const ExecSummaryStory: StoryObj = { name: "Executive Summary", render: () => <ExecSummary /> };
export const ImpactRollupStory: StoryObj = { name: "Impact Rollup", render: () => <ImpactRollup /> };
export const ScenarioStory: StoryObj = { name: "Scenario Projection", render: () => <ScenarioProjection /> };
export const ChatStory: StoryObj = { name: "Chat", render: () => <Chat /> };
export const AiLaunchButtonStory: StoryObj = { name: "AI Launch Button", render: () => <AiLaunchButton /> };
export const AiLoaderStory: StoryObj = { name: "AI Loader", render: () => <AiLoader /> };
export const AiModalChatStory: StoryObj = { name: "AI Modal Chat", render: () => <AiModalChat /> };
export const AiChatHistoryStory: StoryObj = { name: "AI Chat History", render: () => <AiChatHistory /> };
export const AiFeedbackSourcesStory: StoryObj = { name: "AI Feedback Sources", render: () => <AiFeedbackSources /> };
export const DagGraphStory: StoryObj = { name: "DAG Graph Kit", render: () => <DagGraphKit /> };
